return {
  cmd = { "prettierls", "--stdio" },
  filetypes = {
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "vue",
    "css",
    "scss",
    "less",
    "html",
    "json",
    "jsonc",
    "yaml",
    "markdown",
    "markdown.mdx",
    "graphql",
    "handlebars",
    "svelte",
    "astro",
    "htmlangular",
  },
  root_markers = { ".git", ".jj", "node_modules/prettier" },
  single_file_support = true,
  settings = {},
}
